env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
language: ruby
rvm:
  - 2.7.0
before_install: 
  - gem install bundler -v 2.1.4
  - bundle install
notifications:
  - false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
services:
  - postgresql 
addons:
    postgresql: '9.6'
scripts:
  - bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT